disallowed-types = [
    { path = "std::collections::HashMap", reason = "use ra_hash::FxHashMap" },
    { path = "std::collections::HashSet", reason = "use ra_hash::FxHashSet" },
    { path = "std::collections::hash_map::RandomState", reason = "use ra_hash::FxBuildHasher" }
]

disallowed-methods = [
    { path = "std::process::Command::new", reason = "use `toolchain::command` instead as it forces the choice of a working directory" },
]
